name: certabodriver
description: A Certabo-Chessboard Driver written in pure Dart
version: 0.0.4
repository: https://github.com/mono424/certabodriver
homepage: https://khad.im

environment:
  sdk: ">=2.18.0 <3.0.0"
